Controllers/IssuanceController.cs
using Microsoft.AspNetCore.Mvc;
using PurchaseManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PurchaseManagementSystem.Controllers
{
    public class IssuanceController : Controller
    {
        public readonly ConnectionStringClass connectionStringClass;
        public IssuanceController(ConnectionStringClass cc)
        {
            this.connectionStringClass = cc;
        }
        public IActionResult Index()
        {
            IList<Issuance> issuance = connectionStringClass.issuances.OrderByDescending(x => x.iss_id).ToList();
            return View(issuance);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Issuance issuance)
        {
            if (issuance != null)
            {
                connectionStringClass.issuances.Add(issuance);
                connectionStringClass.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Issuance issuance = connectionStringClass.issuances.Where(x => x.iss_id == id).SingleOrDefault();
            return View(issuance);
        }
        [HttpPost]
        public IActionResult Edit(Issuance issuance)
        {
            Issuance issuance1 = connectionStringClass.issuances.Where(x => x.iss_id == issuance.iss_id).SingleOrDefault();
            issuance1.iss_date = issuance.iss_date;
            issuance1.emp_name = issuance.emp_name;
            issuance1.qnty = issuance.qnty;
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Issuance issuance = connectionStringClass.issuances.Where(x => x.iss_id == id).SingleOrDefault();
            return View(issuance);
        }
        [HttpPost]
        public IActionResult Delete(Issuance issuance)
        {
            Issuance issuance1 = connectionStringClass.issuances.Where(x => x.iss_id == issuance.iss_id).SingleOrDefault();
            connectionStringClass.issuances.Remove(issuance1);
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            Issuance issuance = connectionStringClass.issuances.Where(x => x.iss_id == id).SingleOrDefault();
            return View(issuance);
        }
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using PurchaseManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PurchaseManagementSystem.Controllers
{
    public class ItemController : Controller
    {
        public readonly ConnectionStringClass connectionStringClass;
        public ItemController(ConnectionStringClass cs)
        {
            this.connectionStringClass = cs;
        }
        public IActionResult Index()
        {
            IList<Item> list = connectionStringClass.items.OrderByDescending(z => z.item_id).ToList();
            return View(list);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Item item)
        {
            if (item != null)
            {
                connectionStringClass.items.Add(item);
                connectionStringClass.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Item item = connectionStringClass.items.Where(x => x.item_id == id).SingleOrDefault();         
            return View(item);
        }
        [HttpPost]
        public IActionResult Edit(Item item)
        {
            Item item1 = connectionStringClass.items.Where(x=>x.item_id == item.item_id).SingleOrDefault();
            item1.item_name = item.item_name;
            item1.item_status = item.item_status;
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Item item = connectionStringClass.items.Where(x => x.item_id == id).SingleOrDefault();
            return View(item);
        }
        [HttpPost]
        public IActionResult Delete(Item item)
        {
            Item item1 = connectionStringClass.items.Where(x => x.item_id == item.item_id).SingleOrDefault();
            connectionStringClass.items.Remove(item1);
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
            
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            Item item = connectionStringClass.items.Where(x => x.item_id == id).SingleOrDefault();
            return View(item);
        }


    }
}

Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using PurchaseManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PurchaseManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        public readonly ConnectionStringClass connectionStringClass;
        public PurchaseController(ConnectionStringClass cc)
        {
            this.connectionStringClass = cc;
        }
        public IActionResult Index()
        {
            IList<Purchase> purchase = connectionStringClass.purchases.OrderByDescending(x => x.pur_id).ToList();
            return View(purchase);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Purchase purchase)
        {
            if (purchase != null)
            {
                connectionStringClass.purchases.Add(purchase);
                connectionStringClass.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Purchase purchase = connectionStringClass.purchases.Where(x => x.pur_id == id).SingleOrDefault();
            return View(purchase);
        }
        [HttpPost]
        public IActionResult Edit(Purchase purchase)
        {
            Purchase purchase1 = connectionStringClass.purchases.Where(x => x.pur_id == purchase.pur_id).SingleOrDefault();
            purchase1.pur_item = purchase.pur_item;
            purchase1.pur_price = purchase.pur_price;
            purchase1.pur_qnty = purchase.pur_qnty;
            purchase1.vendor = purchase.vendor;
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Purchase purchase = connectionStringClass.purchases.Where(x => x.pur_id == id).SingleOrDefault();
            return View(purchase);
        }
        [HttpPost]
        public IActionResult Delete(Purchase purchase)
        {
            Purchase purchase1 = connectionStringClass.purchases.Where(x => x.pur_id == purchase.pur_id).SingleOrDefault();
            connectionStringClass.purchases.Remove(purchase1);
            connectionStringClass.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Details(int id)
        {
            Purchase purchase = connectionStringClass.purchases.Where(x => x.pur_id == id).SingleOrDefault();
            return View(purchase);
        }
    }
}

Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using PurchaseManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PurchaseManagementSystem.Controllers
{
    public class ReportController : Controller
    {
        private readonly ConnectionStringClass connectionStringClass;

        public ReportController(ConnectionStringClass cc)
        {
            connectionStringClass = cc;
        }
        public IList<Item> Items;

        public IList<Purchase> purchases;

        public IList<Issuance> issuances;
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AllItemData()
        {
            return new Rotativa.AspNetCore.ViewAsPdf(connectionStringClass.items.OrderBy(x => x.item_id).ToList());
        }
        [HttpGet]
        public IActionResult ItemData()
        {
            Items = connectionStringClass.items.OrderBy(x => x.item_id).ToList();
            return View(Items);
        }

        [HttpPost]
        public IActionResult SearchItemData(string Data)
        {
            DataClass data = new DataClass(connectionStringClass);
            Items = data.getItemsData(Data);
            TempData["Data"] = Data;
            return View(Items);
        }

        [HttpGet]
        public IActionResult ItemReport()
        {
            DataClass data = new DataClass(connectionStringClass);
            var myData = TempData["Data"];
            IList<Item> searchItems = data.getItemsData(myData.ToString());
            return new Rotativa.AspNetCore.ViewAsPdf(searchItems);
        }

        [HttpGet]
        public IActionResult ALLPurchaseData()
        {
            return new Rotativa.AspNetCore.ViewAsPdf(connectionStringClass.purchases.OrderBy(x => x.pur_id).ToList());
        }
        [HttpGet]
        public IActionResult PurchaseData()
        {
            purchases = connectionStringClass.purchases.OrderBy(x => x.pur_id).ToList();
            return View(purchases);
        }

        [HttpPost]
        public IActionResult searchPurchaseData(string Data)
        {
            DataClass dataClass = new DataClass(connectionStringClass);
            purchases = dataClass.getPurchasesData(Data);
            TempData["Data"] = Data;
            return View(purchases);

        }
        [HttpGet]
        public IActionResult purchaseReport()
        {
            DataClass dataClass = new DataClass(connectionStringClass);
            var myList = TempData["Data"];
            IList<Purchase> purchasesList = dataClass.getPurchasesData(myList.ToString());
            return new Rotativa.AspNetCore.ViewAsPdf(purchasesList);
        }

        [HttpGet]
        public IActionResult ALLIssuanceReport()
        {
            return new Rotativa.AspNetCore.ViewAsPdf(connectionStringClass.issuances.OrderBy(x => x.iss_id).ToList());
        }
        [HttpGet]
        public IActionResult IssuanceData()
        {
            IList<Issuance> list = connectionStringClass.issuances.OrderBy(x => x.iss_id).ToList();
            return View(list);
        }
        [HttpPost]
        public IActionResult showIssuance(string Data)
        {
            DataClass data = new DataClass(connectionStringClass);
            issuances = data.getIssuancesData(Data);
            TempData["data"] = Data;
            return View(issuances);

        }
        [HttpGet]
        public IActionResult issuanceReport()
        {
            DataClass data = new DataClass(connectionStringClass);
            var myList = TempData["data"];
            IList<Issuance> myData = data.getIssuancesData(myList.ToString());
            return new Rotativa.AspNetCore.ViewAsPdf(myData);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>PurchaseManagement</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="~/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            @*<a href="index2.html" class="logo"><b>Admin</b>LTE</a>*@
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span style="color:white"></span>
                    <span style="color:white">Purchase Management System<i class="fa fa-shopping-cart"></i></span>

                </a>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Niaz</p>

                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search..." />
                        <span class="input-group-btn">
                            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    @*<li class="header">MAIN NAVIGATION</li>*@
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Home</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")<i class="fa fa-book"></i>Home</li>
                            <li>@Html.ActionLink("About Us", "About", "Home")<i class="fa fa-book"></i>About Us</li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Home")<i class="fa fa-book"></i>Contact Us</li>
                        </ul>
                    </li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Transactions</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Item Section", "Index", "Item")<i class="fa fa-book"></i>Item Section</li>
                            <li>@Html.ActionLink("Purchase Section", "Index", "Purchase")<i class="fa fa-book"></i>Purchase Section</li>
                            <li>@Html.ActionLink("Issuance Section", "Index", "Issuance")<i class="fa fa-book"></i>Issuance Section</li>
                        </ul>
                    </li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Reports</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Item Report", "ItemData", "Report")<i class="fa fa-circle-o"></i>Item Report</li>
                            <li>@Html.ActionLink("Purchase Report", "PurchaseData", "Report")<i class="fa fa-circle-o"></i>Purchase Report</li>
                            <li>@Html.ActionLink("Issuance Report", "IssuanceData", "Report")<i class="fa fa-circle-o"></i>Issuance Report</li>
                        </ul>
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Right side column. Contains the navbar and content of the page -->
        <div class="content-wrapper">

            
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section><!-- /.content -->

        </div><!-- /.content-wrapper -->
       
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div><!-- ./wrapper -->
    <!-- jQuery 2.1.3 -->
    <script src="~/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="~/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/plugins/morris/morris.min.js" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="~/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/knob/jquery.knob.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="~/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="~/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='~/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/app.min.js" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js" type="text/javascript"></script>


    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js" type="text/javascript"></script>
</body>
</html>